"""initial schema

Revision ID: 51e8090300d1
Revises: 
Create Date: 2026-05-25 22:49:42.130160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e8090300d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('name_ar', sa.String(length=150), nullable=True),
    sa.Column('type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='accounttype'), nullable=False),
    sa.Column('normal_side', sa.Enum('DEBIT', 'CREDIT', name='normalside'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_company_account_code')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_company_id'), ['company_id'], unique=False)

    op.create_table('agent_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_messages_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_created_at'), ['created_at'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_company_id'), ['company_id'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('contract_type', sa.Enum('FULL_TIME', 'PART_TIME', 'TEMPORARY', name='contracttype'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'TERMINATED', name='employeestatus'), nullable=True),
    sa.Column('basic_salary', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('allowances', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('deductions', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('termination_reason', sa.Enum('RESIGNATION', 'DISMISSAL', 'CONTRACT_END', 'OTHER', name='terminationreason'), nullable=True),
    sa.Column('termination_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_employee_number'), ['employee_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_status'), ['status'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('is_reversal', sa.Boolean(), nullable=True),
    sa.Column('reversal_of', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('pause_reason', sa.Text(), nullable=True),
    sa.Column('paused_by_id', sa.Integer(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('reactivate_reason', sa.Text(), nullable=True),
    sa.Column('reactivated_by_id', sa.Integer(), nullable=True),
    sa.Column('reactivated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paused_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reactivated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reversal_of'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_number'), ['number'], unique=False)

    op.create_table('journal_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_templates_company_id'), ['company_id'], unique=False)

    op.create_table('number_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'doc_type', name='uq_sequence_company_type')
    )
    with op.batch_alter_table('number_sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_number_sequences_company_id'), ['company_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('default_tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_company_id'), ['company_id'], unique=False)

    op.create_table('user_companies',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'company_id')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('bank_account', sa.String(length=100), nullable=True),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_company_id'), ['company_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('invoice_discount_type', sa.Enum('NONE', 'PERCENT', 'FIXED', name='discounttype'), nullable=True),
    sa.Column('invoice_discount_value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('invoice_discount_amount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('taxable_base', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED', name='invoicestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('send_reminders', sa.Boolean(), nullable=True),
    sa.Column('reminder_7d_sent_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_3d_sent_at', sa.DateTime(), nullable=True),
    sa.Column('overdue_notified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_company_invoice_number')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_company_id'), ['company_id'], unique=False)

    op.create_table('journal_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATED', 'PAUSED', 'REACTIVATED', 'REVERSED', 'EXPORTED', name='journalaction'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_audits_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_audits_entry_id'), ['entry_id'], unique=False)

    op.create_table('journal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('credit', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('debit_base', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('credit_base', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_lines_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_lines_entry_id'), ['entry_id'], unique=False)

    op.create_table('journal_template_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('credit', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['journal_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('name_ar', sa.String(length=50), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_pm_company_name')
    )
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_methods_company_id'), ['company_id'], unique=False)

    op.create_table('payroll_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('total_gross', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_net', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_year', 'period_month', name='uq_payroll_period')
    )
    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_runs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_runs_number'), ['number'], unique=False)

    op.create_table('recurring_journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='recurrencefrequency'), nullable=False),
    sa.Column('next_run_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['journal_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_journals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_journals_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_journals_next_run_date'), ['next_run_date'], unique=False)

    op.create_table('vendor_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('supplier_invoice_number', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'BANK', 'CREDIT', name='vendorbillpaymentmethod'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED', name='vendorbillstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_vendor_bill_number')
    )
    with op.batch_alter_table('vendor_bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_bills_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_bills_number'), ['number'], unique=False)

    op.create_table('credit_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('used_amount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_notes_company_id'), ['company_id'], unique=False)

    op.create_table('fixed_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('salvage_value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('useful_life_years', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('source_bill_id', sa.Integer(), nullable=True),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('is_disposed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_bill_id'], ['vendor_bills.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fixed_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fixed_assets_company_id'), ['company_id'], unique=False)

    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('discount_type', sa.Enum('NONE', 'PERCENT', 'FIXED', name='discounttype'), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=True),
    sa.Column('basic', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('allowances', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('overtime', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bonus', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('deductions', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('absence_deduction', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('late_deduction', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('advance_deduction', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['payroll_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('FULL', 'PARTIAL', 'CREDIT_NOTE', name='refundtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_bill_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['vendor_bills.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depreciation_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('book_value_after', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['fixed_assets.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'period_year', 'period_month', name='uq_depreciation_asset_period')
    )
    with op.batch_alter_table('depreciation_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_depreciation_entries_created_at'), ['created_at'], unique=False)

    op.create_table('vendor_bill_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('line_type', sa.Enum('EXPENSE', 'FIXED_ASSET', 'INVENTORY', name='billlinetype'), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('useful_life_years', sa.Integer(), nullable=True),
    sa.Column('salvage_value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('created_asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['bill_id'], ['vendor_bills.id'], ),
    sa.ForeignKeyConstraint(['created_asset_id'], ['fixed_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_bill_items')
    with op.batch_alter_table('depreciation_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_depreciation_entries_created_at'))

    op.drop_table('depreciation_entries')
    op.drop_table('vendor_bill_payments')
    op.drop_table('refunds')
    op.drop_table('payroll_lines')
    op.drop_table('payments')
    op.drop_table('invoice_items')
    with op.batch_alter_table('fixed_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fixed_assets_company_id'))

    op.drop_table('fixed_assets')
    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_notes_company_id'))

    op.drop_table('credit_notes')
    with op.batch_alter_table('vendor_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_bills_number'))
        batch_op.drop_index(batch_op.f('ix_vendor_bills_company_id'))

    op.drop_table('vendor_bills')
    with op.batch_alter_table('recurring_journals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_journals_next_run_date'))
        batch_op.drop_index(batch_op.f('ix_recurring_journals_company_id'))

    op.drop_table('recurring_journals')
    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_runs_number'))
        batch_op.drop_index(batch_op.f('ix_payroll_runs_company_id'))

    op.drop_table('payroll_runs')
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_methods_company_id'))

    op.drop_table('payment_methods')
    op.drop_table('journal_template_lines')
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_lines_entry_id'))
        batch_op.drop_index(batch_op.f('ix_journal_lines_account_id'))

    op.drop_table('journal_lines')
    with op.batch_alter_table('journal_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_audits_entry_id'))
        batch_op.drop_index(batch_op.f('ix_journal_audits_created_at'))

    op.drop_table('journal_audits')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_company_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_company_id'))

    op.drop_table('vendors')
    op.drop_table('user_companies')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_company_id'))

    op.drop_table('products')
    with op.batch_alter_table('number_sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_number_sequences_company_id'))

    op.drop_table('number_sequences')
    with op.batch_alter_table('journal_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_templates_company_id'))

    op.drop_table('journal_templates')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_number'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_is_active'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_company_id'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_status'))
        batch_op.drop_index(batch_op.f('ix_employees_employee_number'))
        batch_op.drop_index(batch_op.f('ix_employees_company_id'))

    op.drop_table('employees')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_company_id'))

    op.drop_table('customers')
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_company_id'))

    op.drop_table('agent_messages')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_company_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('companies')
    # ### end Alembic commands ###
